// This file is auto-generated by `npm run db:types`.
// DO NOT EDIT MANUALLY. Run `npm run db:types` after schema changes.
//
// Placeholder created during Phase 11 Plan 01.
// Replace with real generated types after running `npx supabase gen types`.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          role: string;
          display_name: string;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id: string;
          role?: string;
          display_name: string;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          role?: string;
          display_name?: string;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      sessions: {
        Row: {
          id: string;
          name: string;
          mode: string;
          status: string;
          notes: string;
          review_notes: string | null;
          created_by: string;
          assigned_to: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          mode: string;
          status?: string;
          notes?: string;
          review_notes?: string | null;
          created_by: string;
          assigned_to?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          mode?: string;
          status?: string;
          notes?: string;
          review_notes?: string | null;
          created_by?: string;
          assigned_to?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      items: {
        Row: {
          id: string;
          session_id: string;
          mode: string;
          receipt_number: string | null;
          title: string | null;
          description: string | null;
          condition: string | null;
          estimate: string | null;
          measurements: string | null;
          category: string | null;
          transcript: string | null;
          ai_status: string;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          session_id: string;
          mode: string;
          receipt_number?: string | null;
          title?: string | null;
          description?: string | null;
          condition?: string | null;
          estimate?: string | null;
          measurements?: string | null;
          category?: string | null;
          transcript?: string | null;
          ai_status?: string;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          session_id?: string;
          mode?: string;
          receipt_number?: string | null;
          title?: string | null;
          description?: string | null;
          condition?: string | null;
          estimate?: string | null;
          measurements?: string | null;
          category?: string | null;
          transcript?: string | null;
          ai_status?: string;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      export_history: {
        Row: {
          id: string;
          session_id: string;
          session_name: string;
          session_mode: string;
          item_count: number;
          exported_at: string;
          exported_by: string;
        };
        Insert: {
          id?: string;
          session_id: string;
          session_name: string;
          session_mode: string;
          item_count: number;
          exported_at?: string;
          exported_by: string;
        };
        Update: {
          id?: string;
          session_id?: string;
          session_name?: string;
          session_mode?: string;
          item_count?: number;
          exported_at?: string;
          exported_by?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];
export type Insertable<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];
export type Updatable<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];
