steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - cataloger-api/Dockerfile
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/potomack/cataloger-api
      - .
images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/potomack/cataloger-api
